import type { TypographyToken } from './types';

export const typographyTokens = {
  display: {
    description: 'Large KPIs and hero titles',
    fontFamily: 'Poppins',
    fontStyle: 'Bold',
    fontWeight: 700,
    fontSize: 48,
    lineHeight: 56,
    letterSpacing: '-1%',
  },
  h1: {
    description: 'Page titles',
    fontFamily: 'Poppins',
    fontStyle: 'SemiBold',
    fontWeight: 600,
    fontSize: 36,
    lineHeight: 44,
    letterSpacing: '0.5%',
  },
  h2: {
    description: 'Section headers',
    fontFamily: 'Poppins',
    fontStyle: 'SemiBold',
    fontWeight: 600,
    fontSize: 28,
    lineHeight: 36,
    letterSpacing: '0%',
  },
  h3: {
    description: 'Module and card titles',
    fontFamily: 'Poppins',
    fontStyle: 'Medium',
    fontWeight: 500,
    fontSize: 22,
    lineHeight: 32,
    letterSpacing: '0%',
  },
  h4: {
    description: 'Subtitles and supporting headers',
    fontFamily: 'Poppins',
    fontStyle: 'Medium',
    fontWeight: 500,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: '0%',
  },
  bodyLarge: {
    description: 'Main body content',
    fontFamily: 'Poppins',
    fontStyle: 'Regular',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: '0%',
  },
  bodyBase: {
    description: 'Paragraphs and content blocks',
    fontFamily: 'Poppins',
    fontStyle: 'Regular',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: '0%',
  },
  bodySmall: {
    description: '',
    fontFamily: 'Poppins',
    fontStyle: 'Light',
    fontWeight: 300,
    fontSize: 14,
    lineHeight: 'normal',
    letterSpacing: '0%',
  },
  caption: {
    description: 'Labels and captions',
    fontFamily: 'Poppins',
    fontStyle: 'Medium',
    fontWeight: 500,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: '0%',
  },
  button: {
    description: 'Buttons',
    fontFamily: 'Poppins',
    fontStyle: 'Regular',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 16,
    letterSpacing: '0%',
  },
  input: {
    description: 'Form fields',
    fontFamily: 'Inter',
    fontStyle: 'Regular',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: '0%',
  },
} as const satisfies Record<string, TypographyToken>;

export type TypographyTokenName = keyof typeof typographyTokens;
